vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        doctors:
            uri_prefix: /images/doctors
            upload_destination: '%kernel.project_dir%/public/images/doctors'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer